
version: '2.1'
services:
  mariadb:
    extends:
      file: docker-compose-base.yml
      service: base-mariadb
    container_name: ${CONTAINER_HOST_NAME:-mariadb}
    hostname: ${CONTAINER_HOST_NAME:-mariadb}
    network_mode: bridge
    ports:
    - "${MARIADB_3306_PORT:-3306}:3306"
    - "${MARIADB_5444_PORT:-5444}:5444"
    - "${MARIADB_5567_PORT:-5567}:5567"
    - "${MARIADB_5568_PORT:-5568}:5568"
    restart: always
    volumes:
    - data:/var/lib/mysql
    - log:/var/log

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
  log:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/log
      o: bind
