
version: '2.1'
services:
  base-mariadb:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_IMAGE_TAG=${IMAGE_ARG_IMAGE_TAG:-10.1.34}
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_pass} # changeme
    image: ${IMAGE_PREFIX:-cloudready/}${IMAGE_NAME:-mariadb}:${IMAGE_TAG:-10.1.34-SNAPSHOT}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.mariadb}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/mariadb/standalone}
    restart: always
