
version: '2.1'
services:
  mariadb-develop:
    extends:
      file: docker-compose-base.yml
      service: base-mariadb
    container_name: ${CONTAINER_HOST_NAME:-standalone.mariadb}
    hostname: ${CONTAINER_HOST_NAME:-standalone.mariadb}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.mariadb}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/mariadb/standalone}
    networks:
      local-network:
        ipv4_address: ${IPV4_ADDRESS:-172.16.238.101}
        #ipv6_address: ${IPV6_ADDRESS:-2001:3984:3989::101}
    ports:
    - "${EXTERNAL_MARIADB_3306_PORT:-3306}:3306"
    - "${EXTERNAL_MARIADB_5444_PORT:-5444}:5444"
    - "${EXTERNAL_MARIADB_5567_PORT:-5567}:5567"
    - "${EXTERNAL_MARIADB_5568_PORT:-5568}:5568"
    restart: always
    volumes:
    - data:/var/lib/mysql
    - log:/var/log

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
  log:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/log
      o: bind
